spring:
  datasource:
    url: "jdbc:postgresql://10.111.193.3:5432/smartstock"
    username: "smartstock"
    password: "Root@123"
    driverClassName: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: "false"
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: "false"
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  cloud:
    gcp:
      sql:
        enabled: true
        instance-connection-name: "hu18-groupb-java:asia-south1:hu20cicd1nik"
        database-name: "smartstock"
